### ISSUE TITLE
settings not showing, everything else works

### ISSUE THREAD

**Issue by huhridge** [FlafyDev/spotify-css-editor#1]
![Screenshot 2022-02-03 at 09 42 59](https://user-images.githubusercontent.com/67046436/152280031-d22cd610-9317-460d-86d5-ac32286866c1.jpg)

You probably need some delay so that it renders, maybe, but I also maybe wrong

**Comment by FlafyDev** [comment]
It seems to be an issue with [spicetify-creator-settings-plugin](https://github.com/FlafyDev/spicetify-creator-settings-plugin).
Is this error consistent? Which Spotify version do you have? I can't replicate it on my machine...
Anyway, I added a delay to try again after 1000ms if it fails to find the button in your error but I don't think that's what causing the error.

**Comment by huhridge** [comment]
Yeah, it happens every time, I am on 1.1.77.
You're right adding delay did nothing.

**Comment by huhridge** [comment]
Solved It!
