### ISSUE TITLE
Where?!

### ISSUE THREAD

**Issue by 1abs90** [FlafyDev/spotify-css-editor#5]
I'm probably just being stupid, but i cant seem to find where i find the menu, for the css editor. help.

**Comment by FlafyDev** [comment]
It should be in the "Settings" options here
![image](https://user-images.githubusercontent.com/44374434/163058476-27902700-4d37-48d1-a95e-5bc45f7a8dc8.png)

**Comment by 1abs90** [comment]
> It should be in the "Settings" options here ![image](https://user-images.githubusercontent.com/44374434/163058476-27902700-4d37-48d1-a95e-5bc45f7a8dc8.png)

Yes but i cant find it in there, im using a theme and a few extensions, does that make a problem?
![image](https://user-images.githubusercontent.com/103536674/163061770-c8d66afb-0538-408e-a92b-112f520dc5d7.png)
![image](https://user-images.githubusercontent.com/103536674/163061773-d809e4e4-81be-4ed3-9a34-50628207f110.png)
![image](https://user-images.githubusercontent.com/103536674/163061775-12e8f311-305f-4384-917f-f202e9f4a0a2.png)

**Comment by FlafyDev** [comment]
Uh, so this extension is still using `spcr-settings` version 0.1.3.
I will need to update it to 1.0.2.

**Comment by FlafyDev** [comment]
Updated. Please check if it's working properly when the extension updates in the marketplace(or you can download it manually).

**Comment by 1abs90** [comment]
Thanks! I'll check it out tomorrow morning :), will get straight back at ya if any problems are found.
