### ISSUE TITLE
I typed "Display: none" in the editor help.

### ISSUE THREAD

**Issue by Kevgmd** [FlafyDev/spotify-css-editor#6]
i typed `Display: none` in the universal selector to test if the extension is working and then everything became white and i don't know how to revert it back, i'll need to reinstall the extension? If yes, how do i do it? (Sorry for the dumb issue)

**Comment by FlafyDev** [comment]
You can open devtools and edit the extension's data in Local Storage. I think it's named `css-editor.css`.

**Comment by Kevgmd** [comment]
> You can open devtools and edit the extension's data in Local Storage. I think it's named `css-editor.css`.

Perfect! The data name is correct, many thanks.

**Comment by 0pl1v10n** [comment]
how do i get this on arch linux
